linnmon-master/linnmon-master/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'orders/index'
  get 'orders/edit'
  get 'orders/update'
  resources :foodcourts do
    member do
      get 'add_restaraunt', to: 'foodcourts#add_restaraunt', as: 'add_restaraunt'
    end
  end
  #resources :cart_items
  get 'home', to: "home#home", as: 'home'

  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :sessions, except: [:update, :index]

  resources :restaraunts do
    resources :menu_categories
    resources :menu_items
  end
  resources :cuisines
  resources :users

  root to: "home#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount Api::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/docs"
end

linnmon-master/linnmon-master/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

linnmon-master/linnmon-master/app/models/cart_item.rb
class CartItem < ApplicationRecord
  include ActiveModel::Serialization
  belongs_to :cart
  belongs_to :menu_item
end

linnmon-master/linnmon-master/app/models/cuisine.rb
class Cuisine < ApplicationRecord
end

linnmon-master/linnmon-master/app/models/foodcourt.rb
class Foodcourt < ApplicationRecord
  belongs_to :user
  has_many :foodcourt_restaraunts
  has_many :restaraunts, through: :foodcourt_restaraunts

  reverse_geocoded_by :latitude, :longitude
end

linnmon-master/linnmon-master/app/models/matcher_profile.rb
class MatcherProfile < ApplicationRecord
  belongs_to :user

  def queue
    bad_ids = MatcherSelection.where(matcher_profile_id: id).pluck(:matchee_id).to_a
    MatcherProfile.where(looking_for: looking_for == 0 ? 1 : 0).where.not(id: [bad_ids, id].flatten).order('random()')
  end

  def likes(matcher_profile)
    MatcherSelection.create_or_find_by(matcher_profile_id: id, matchee_id: matcher_profile.id, is_liked: true)
    Rails.cache.delete("matcherqueuefor:#{id}")
    if MatcherSelection.where(matcher_profile_id: matcher_profile.id, matchee_id: id).blank?
      :it_sucks
    else
      :mutual
    end
  end

  def dislikes(matcher_profile)
    MatcherSelection.create_or_find_by(matcher_profile_id: id, matchee_id: matcher_profile.id, is_liked: false)
  end
end

linnmon-master/linnmon-master/app/models/matcher_selection.rb
class MatcherSelection < ApplicationRecord
  belongs_to :matcher_profile
end

linnmon-master/linnmon-master/app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :restaraunt
  belongs_to :user

  has_many :menu_items
end

linnmon-master/linnmon-master/app/models/menu_item.rb
class MenuItem < ApplicationRecord
  include ActiveModel::Serialization
  belongs_to :menu_category
  belongs_to :restaraunt

  has_one_attached :photo
end

linnmon-master/linnmon-master/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

linnmon-master/linnmon-master/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

linnmon-master/linnmon-master/app/models/restaraunt.rb
class Restaraunt < ApplicationRecord
  has_one :cuisine
  belongs_to :user

  has_many :menu_categories
  has_many :menu_items

  reverse_geocoded_by :latitude, :longitude

  def cuisine
    Cuisine.find(id)
  end

  def foodcourt

  end
end

linnmon-master/linnmon-master/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  ROLES = { superadmin: 0, chainadmin: 1, personeel: 2, ordinary: 3 }.freeze
  has_secure_password

  has_many :user_tokens
  has_many :orders

  has_one :matcher_profile

  def cart_items
    CartItem.where(cart_id: Cart.find_by_user_id(id))
  end

  def self.from_vk_token(token)
    vk = VkontakteApi::Client.new('e53196dbe53196dbe53196db0de55c8d9dee531e53196dbb8bfb196631813a421195732')
    info = vk.users.get(user_id: token, fields: %i[id first_name last_name photo_max_orig])[0]

    user = User.where(vk_id: info.id).first_or_create
    user.password = "#{info.first_name} #{info.last_name}#{info.last_name}#{info.last_name}"
    user.name = "#{info.first_name} #{info.last_name}"
    user.login = "vkuser#{info.id}"
    user.vk_id = info.id
    user.photo_url = info.photo_max_orig
    user.role = User::ROLES[:ordinary]
    Cart.find_or_create_by(user_id: user.id)
    user.save!

    user
  end

  def self.with_token(token)
    UserToken.find_by_token!(token).user
  end
end

linnmon-master/linnmon-master/app/models/user_token.rb
class UserToken < ApplicationRecord
  TTL = 24.hours

  belongs_to :user

  before_create :generate_token

  private

  def generate_token
    t = nil
    loop do
      t = SecureRandom.hex(20)
      break t unless UserToken.where(token: token).exists?
    end

    self.token = t
  end
end

linnmon-master/linnmon-master/app/controllers/menu_items_controller.rb
# frozen_string_literal: true

class MenuItemsController < ApplicationController
  before_action :set_menu_item, only: %i[show edit update destroy]

  # GET /menu_items
  # GET /menu_items.json
  def index
    @menu_items = Restaraunt.find(params[:restaraunt_id]).menu_items
    @menu_categories = Restaraunt.find(params[:restaraunt_id]).menu_categories
    @menu_category = MenuCategory.new
  end

  # GET /menu_items/1
  # GET /menu_items/1.json
  def show; end

  # GET /menu_items/new
  def new
    @menu_item = MenuItem.new
  end

  # GET /menu_items/1/edit
  def edit; end

  # POST /menu_items
  # POST /menu_items.json
  def create
    @menu_item = MenuItem.new(menu_item_params)
    @menu_item.restaraunt_id = params[:restaraunt_id]

    respond_to do |format|
      if @menu_item.save
        format.html { redirect_to restaraunt_menu_items_path, notice: 'Menu item was successfully created.' }
        format.json { render :show, status: :created, location: @menu_item }
      else
        format.html { render :new }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /menu_items/1
  # PATCH/PUT /menu_items/1.json
  def update
    respond_to do |format|
      if @menu_item.update(menu_item_params)
        format.html { redirect_to restaraunt_menu_items_path, notice: 'Menu item was successfully updated.' }
        format.json { render :show, status: :ok, location: @menu_item }
      else
        format.html { render :edit }
        format.json { render json: @menu_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /menu_items/1
  # DELETE /menu_items/1.json
  def destroy
    @menu_item.destroy
    respond_to do |format|
      format.html { redirect_to restaraunt_menu_items_path, notice: 'Menu item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_menu_item
    @menu_item = MenuItem.find(params[:id])
    @restaraunt = Restaraunt.find(params[:restaraunt_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def menu_item_params
    params.require(:menu_item).permit(:name, :description, :menu_category_id, :price, :photo)
  end
end

linnmon-master/linnmon-master/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

linnmon-master/linnmon-master/app/helpers/carts_helper.rb
module CartsHelper
end

linnmon-master/linnmon-master/app/helpers/cuisines_helper.rb
module CuisinesHelper
end

linnmon-master/linnmon-master/app/helpers/foodcourts_helper.rb
module FoodcourtsHelper
end

linnmon-master/linnmon-master/app/helpers/home_helper.rb
module HomeHelper
end

linnmon-master/linnmon-master/app/helpers/menu_items_helper.rb
module MenuItemsHelper
end

linnmon-master/linnmon-master/app/helpers/orders_helper.rb
module OrdersHelper
end

linnmon-master/linnmon-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

linnmon-master/linnmon-master/app/helpers/users_helper.rb
module UsersHelper
end

linnmon-master/linnmon-master/app/views/menu_items/_form.html.erb
<%
  if params[:action] == 'new' || params[:action] == 'create'
    path = restaraunt_menu_items_path(params[:restaraunt_id])
  else
    path = restaraunt_menu_item_path(params[:restaraunt_id], params[:id])
  end
%>

<%= form_with(model: [restaraunt, menu_item], local: true, url: path) do |form| %>
  <% if menu_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(menu_item.errors.count, "error") %> prohibited this menu_item from being saved:</h2>

      <ul>
        <% menu_item.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :photo %>
    <%= form.file_field :photo %>
  </div>

  <div class="field">
    <%= form.label :menu_category_id %>
    <%= form.text_field :menu_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

linnmon-master/linnmon-master/app/views/menu_items/_menu_item.html.erb
<div class="Box box-shadow-medium col-12 col-sm-6 col-md-4 col-lg-2 mx-2 mb- Box--condensed">
  <ul>
    <li class="Box-row">
      <% if menu_item.photo.attached? %>
        <%= image_tag rails_representation_url(menu_item.photo.variant(combine_options: {  gravity: "center", resize: "300x300^", crop: "300x300+0+0" }), only_path: true), style: 'max-width:100%' %>
      <% else %>
        нет картинки
      <% end %>
    </li>
    <li class="Box-row text-center">
      <h4><%= menu_item.name %></h4>
      <div class="mt-1">
        <%= menu_item.price %> руб.
      </div>
    </li>
    <li class="Box-row">
      <%= menu_item.description %>
    </li>
    <li class="Box-row">
      <%= link_to 'Edit', edit_restaraunt_menu_item_path(params[:restaraunt_id], menu_item) %> / <%= link_to 'Destroy', restaraunt_menu_item_path(params[:restaraunt_id], menu_item), method: :delete, data: { confirm: 'Are you sure?' } %>
    </li>
  </ul>
</div>

linnmon-master/linnmon-master/app/views/menu_items/edit.html.erb
<h1>Editing Menu Item</h1>

<%= render 'form', menu_item: @menu_item, restaraunt: @restaraunt %>

linnmon-master/linnmon-master/app/views/menu_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mb-2">Menu Items
  <%= link_to 'New Menu Item', new_restaraunt_menu_item_path(params[:restaraunt_id]), class: 'btn btn-primary' %>
  <%= link_to 'Menu Categories', restaraunt_menu_categories_path(params[:restaraunt_id]), class: 'btn' %>
</h1>
<div class="d-flex flex-wrap flex-justify-around">
  <%= render @menu_items %>
</div>

linnmon-master/linnmon-master/app/views/menu_items/new.html.erb
<h1>New Menu Item</h1>

<%= render 'form', menu_item: @menu_item, restaraunt: @restaraunt %>

<%= link_to 'Back', restaraunt_menu_items_path(params[:restaraunt_id]) %>

linnmon-master/linnmon-master/app/views/menu_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>

</p>

<p>
  <strong>Description:</strong>
  <%= @menu_item.description %>
</p>

<p>
  <strong>Menu item:</strong>
  <%= @menu_item.menu_item_id %>
</p>

<p>
  <strong>Restaraunt:</strong>
  <%= @menu_item.restaraunt_id %>
</p>

<%= link_to 'Edit', edit_menu_item_path(@menu_item) %> |
<%= link_to 'Back', menu_items_path %>