linnmon-master/linnmon-master/config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do

  get 'orders/index'
  get 'orders/edit'
  get 'orders/update'
  resources :foodcourts do
    member do
      get 'add_restaraunt', to: 'foodcourts#add_restaraunt', as: 'add_restaraunt'
    end
  end
  #resources :cart_items
  get 'home', to: "home#home", as: 'home'

  get 'sessions/destroy', to: 'sessions#destroy', as: 'logout'
  resources :sessions, except: [:update, :index]

  resources :restaraunts do
    resources :menu_categories
    resources :menu_items
  end
  resources :cuisines
  resources :users

  root to: "home#home"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  mount Api::Base, at: "/"
  mount GrapeSwaggerRails::Engine, at: "/docs"
end

linnmon-master/linnmon-master/app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
end

linnmon-master/linnmon-master/app/models/cart_item.rb
class CartItem < ApplicationRecord
  include ActiveModel::Serialization
  belongs_to :cart
  belongs_to :menu_item
end

linnmon-master/linnmon-master/app/models/cuisine.rb
class Cuisine < ApplicationRecord
end

linnmon-master/linnmon-master/app/models/foodcourt.rb
class Foodcourt < ApplicationRecord
  belongs_to :user
  has_many :foodcourt_restaraunts
  has_many :restaraunts, through: :foodcourt_restaraunts

  reverse_geocoded_by :latitude, :longitude
end

linnmon-master/linnmon-master/app/models/matcher_profile.rb
class MatcherProfile < ApplicationRecord
  belongs_to :user

  def queue
    bad_ids = MatcherSelection.where(matcher_profile_id: id).pluck(:matchee_id).to_a
    MatcherProfile.where(looking_for: looking_for == 0 ? 1 : 0).where.not(id: [bad_ids, id].flatten).order('random()')
  end

  def likes(matcher_profile)
    MatcherSelection.create_or_find_by(matcher_profile_id: id, matchee_id: matcher_profile.id, is_liked: true)
    Rails.cache.delete("matcherqueuefor:#{id}")
    if MatcherSelection.where(matcher_profile_id: matcher_profile.id, matchee_id: id).blank?
      :it_sucks
    else
      :mutual
    end
  end

  def dislikes(matcher_profile)
    MatcherSelection.create_or_find_by(matcher_profile_id: id, matchee_id: matcher_profile.id, is_liked: false)
  end
end

linnmon-master/linnmon-master/app/models/matcher_selection.rb
class MatcherSelection < ApplicationRecord
  belongs_to :matcher_profile
end

linnmon-master/linnmon-master/app/models/menu_category.rb
class MenuCategory < ApplicationRecord
  belongs_to :restaraunt
  belongs_to :user

  has_many :menu_items
end

linnmon-master/linnmon-master/app/models/menu_item.rb
class MenuItem < ApplicationRecord
  include ActiveModel::Serialization
  belongs_to :menu_category
  belongs_to :restaraunt

  has_one_attached :photo
end

linnmon-master/linnmon-master/app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  has_many :order_items
end

linnmon-master/linnmon-master/app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :menu_item
end

linnmon-master/linnmon-master/app/models/restaraunt.rb
class Restaraunt < ApplicationRecord
  has_one :cuisine
  belongs_to :user

  has_many :menu_categories
  has_many :menu_items

  reverse_geocoded_by :latitude, :longitude

  def cuisine
    Cuisine.find(id)
  end

  def foodcourt

  end
end

linnmon-master/linnmon-master/app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  ROLES = { superadmin: 0, chainadmin: 1, personeel: 2, ordinary: 3 }.freeze
  has_secure_password

  has_many :user_tokens
  has_many :orders

  has_one :matcher_profile

  def cart_items
    CartItem.where(cart_id: Cart.find_by_user_id(id))
  end

  def self.from_vk_token(token)
    vk = VkontakteApi::Client.new('e53196dbe53196dbe53196db0de55c8d9dee531e53196dbb8bfb196631813a421195732')
    info = vk.users.get(user_id: token, fields: %i[id first_name last_name photo_max_orig])[0]

    user = User.where(vk_id: info.id).first_or_create
    user.password = "#{info.first_name} #{info.last_name}#{info.last_name}#{info.last_name}"
    user.name = "#{info.first_name} #{info.last_name}"
    user.login = "vkuser#{info.id}"
    user.vk_id = info.id
    user.photo_url = info.photo_max_orig
    user.role = User::ROLES[:ordinary]
    Cart.find_or_create_by(user_id: user.id)
    user.save!

    user
  end

  def self.with_token(token)
    UserToken.find_by_token!(token).user
  end
end

linnmon-master/linnmon-master/app/models/user_token.rb
class UserToken < ApplicationRecord
  TTL = 24.hours

  belongs_to :user

  before_create :generate_token

  private

  def generate_token
    t = nil
    loop do
      t = SecureRandom.hex(20)
      break t unless UserToken.where(token: token).exists?
    end

    self.token = t
  end
end

linnmon-master/linnmon-master/app/controllers/restaraunts_controller.rb
class RestarauntsController < ApplicationController
  before_action :set_restaraunt, only: [:show, :edit, :update, :destroy]

  # GET /restaraunts
  # GET /restaraunts.json
  def index
    unless params[:foodcourt_id].nil?
      @foodcourt = Foodcourt.find(params[:foodcourt_id])
      @restaraunts = @foodcourt.restaraunts
    else
      @restaraunts = Restaraunt.where(is_in_foodcourt: false)
    end
  end

  # GET /restaraunts/1
  # GET /restaraunts/1.json
  def show
  end

  # GET /restaraunts/new
  def new
    @restaraunt = Restaraunt.new
  end

  # GET /restaraunts/1/edit
  def edit
  end

  # POST /restaraunts
  # POST /restaraunts.json
  def create
    @restaraunt = Restaraunt.new(restaraunt_params)
    @restaraunt.is_in_foodcourt = false

    respond_to do |format|
      if @restaraunt.save
        format.html { redirect_to @restaraunt, notice: 'Restaraunt was successfully created.' }
        format.json { render :show, status: :created, location: @restaraunt }
      else
        format.html { render :new }
        format.json { render json: @restaraunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaraunts/1
  # PATCH/PUT /restaraunts/1.json
  def update
    respond_to do |format|
      if @restaraunt.update(restaraunt_params)
        format.html { redirect_to @restaraunt, notice: 'Restaraunt was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaraunt }
      else
        format.html { render :edit }
        format.json { render json: @restaraunt.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaraunts/1
  # DELETE /restaraunts/1.json
  def destroy
    @restaraunt.destroy
    respond_to do |format|
      format.html { redirect_to restaraunts_url, notice: 'Restaraunt was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaraunt
      @restaraunt = Restaraunt.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaraunt_params
      params.require(:restaraunt).permit(:address, :latitude, :longitude, :cuisine_id, :name, :description, :price_rating, :user_id)
    end
end

linnmon-master/linnmon-master/app/helpers/cart_items_helper.rb
module CartItemsHelper
end

linnmon-master/linnmon-master/app/helpers/carts_helper.rb
module CartsHelper
end

linnmon-master/linnmon-master/app/helpers/cuisines_helper.rb
module CuisinesHelper
end

linnmon-master/linnmon-master/app/helpers/foodcourts_helper.rb
module FoodcourtsHelper
end

linnmon-master/linnmon-master/app/helpers/home_helper.rb
module HomeHelper
end

linnmon-master/linnmon-master/app/helpers/orders_helper.rb
module OrdersHelper
end

linnmon-master/linnmon-master/app/helpers/restaraunts_helper.rb
module RestarauntsHelper
end

linnmon-master/linnmon-master/app/helpers/sessions_helper.rb
module SessionsHelper
end

linnmon-master/linnmon-master/app/helpers/users_helper.rb
module UsersHelper
end

linnmon-master/linnmon-master/app/views/restaraunts/_form.html.erb
<%= form_with(model: restaraunt, local: true) do |form| %>
  <% if restaraunt.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaraunt.errors.count, "error") %> prohibited this restaraunt from being saved:</h2>

      <ul>
        <% restaraunt.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude %>
  </div>

  <div class="field">
    <%= form.label :cuisine_id %>
    <%= form.text_field :cuisine_id %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_area :description %>
  </div>

  <div class="field">
    <%= form.label :price_rating %>
    <%= form.number_field :price_rating %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

linnmon-master/linnmon-master/app/views/restaraunts/_restaraunt.html.erb
<div class="Box Box--condensed mb-4">
  <div class="Box-header bg-blue-light">
    <h3>
      <%= restaraunt.name %>
    </h3>
  </div>
  <div class="d-flex">
    <div>
      <img src="https://static-maps.yandex.ru/1.x/?ll=<%= restaraunt.longitude %>,<%= restaraunt.latitude %>&size=350,150&z=17&l=map&pt=<%= restaraunt.longitude %>,<%= restaraunt.latitude %>">
    </div>
    <div style="width: 100%">
      <div class="Box-body" style="font-size:1.2em">
        <%= restaraunt.description %>
      </div>
      <ul>
        <li class="Box-row">
          <b><%= restaraunt.address %></b> (<%= restaraunt.latitude %>, <%= restaraunt.longitude %>)
        </li>
        <li class="Box-row">
          <%= Cuisine.find(restaraunt.cuisine_id).name %> <b>кухня</b>
        </li>
        <li class="Box-row">
          <b>Ценовой рейтинг</b>: <%= restaraunt.price_rating %>
        </li>
      </ul>
    </div>
  </div>
  <div class="Box-footer">
    <div class="d-flex flex-justify-between">
      <div>
        <%= link_to 'Orders', '/', class: 'btn btn-keklik' %>
        <%= link_to 'Items', restaraunt_menu_items_path(restaraunt.id), class: 'btn btn-primary' %>
      </div>
      <div><%= link_to 'Edit', edit_restaraunt_path(restaraunt), class: 'btn' %> <%= link_to 'Destroy', restaraunt, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></div>
    </div>
  </div>
</div>

linnmon-master/linnmon-master/app/views/restaraunts/edit.html.erb
<h1>Editing Restaraunt</h1>

<%= render 'form', restaraunt: @restaraunt %>

<%= link_to 'Show', @restaraunt %> |
<%= link_to 'Back', restaraunts_path %>

linnmon-master/linnmon-master/app/views/restaraunts/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="mb-3">Restaraunts <% if params[:foodcourt_id].nil? %> <%= link_to 'New Restaraunt', new_restaraunt_path, class: 'btn btn-primary' %> <% else %> in foodcourt<% end %></h1>

<% unless params[:foodcourt_id].nil? %>
  <div class="my-2"><%= link_to 'Return to foodcourts', foodcourts_path %></div>
<% end %>

<div class="col-md-10 col-lg-7 col-12">
  <%= render @restaraunts %>
</div>

linnmon-master/linnmon-master/app/views/restaraunts/new.html.erb
<h1>New Restaraunt</h1>

<%= render 'form', restaraunt: @restaraunt %>

<%= link_to 'Back', restaraunts_path %>

linnmon-master/linnmon-master/app/views/restaraunts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Address:</strong>
  <%= @restaraunt.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @restaraunt.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @restaraunt.longitude %>
</p>

<p>
  <strong>Cuisine:</strong>
  <%= @restaraunt.cuisine_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @restaraunt.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @restaraunt.description %>
</p>

<p>
  <strong>Price rating:</strong>
  <%= @restaraunt.price_rating %>
</p>

<p>
  <strong>User:</strong>
  <%= @restaraunt.user_id %>
</p>

<%= link_to 'Edit', edit_restaraunt_path(@restaraunt) %> |
<%= link_to 'Back', restaraunts_path %>